esphome:
  name: qtpy
  friendly_name: HDC3021+QtPy
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: adafruit_qtpy_esp32s3_nopsram
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

i2c:
  sda: 41
  scl: 40
  scan: true
  frequency: 100kHz

external_components:
  - source: components

sensor:
  - platform: hdc3020
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 15s
    # humidity_offset: 8.20% # 0xaa
    # temperature_offset: -7.17°C # 0x2a

logger:

wifi:

api:

ota:
  platform: esphome

improv_serial:

web_server:
