esphome:
  name: d1mini
  friendly_name: HDC3021+WeMosD1Mini
  name_add_mac_suffix: true

esp8266:
  board: d1_mini

i2c:
  sda: 4
  scl: 5
  scan: true
  frequency: 100kHz

external_components:
  - source: components

sensor:
  - platform: hdc3020
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

logger:

api:

ota:
  platform: esphome

wifi:

improv_serial:

web_server:
