esphome:
  name: qtpy
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: adafruit_qtpy_esp32s3_nopsram
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    advanced:
      ignore_efuse_mac_crc: false

i2c:
  sda: GPIO41
  scl: GPIO40

external_components:
  - source: components

sensor:
  - platform: hdc3020
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

logger:

wifi:

api:

ota:
  platform: esphome

improv_serial:

web_server:
