esphome:
  name: d1mini
  friendly_name: HDC3021+WeMosD1Mini
  name_add_mac_suffix: true

esp8266:
  board: d1_mini

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  frequency: 100kHz

sensor:
  - platform: hdc3020
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

logger:

api:

ota:
  platform: esphome

wifi:
  ap:
    password: "12345678"

captive_portal:

improv_serial:

web_server:
  port: 80

external_components:
  - source: components
